export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const POST_WORKOUT = 'POST_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
